### ISSUE TITLE
Issue with Dependency Versions and Availability for scim-spring-boot-starter and scim-server

### ISSUE THREAD

**Issue by heureuxchaquejour** [apache/directory-scimple#402]
We've been following the instructions in the [Five Minute Tutorial](https://directory.apache.org/scimple/five-minutes-tutorial.html) associated with this project, and are looking to add dependencies on both scim-spring-boot-starter and scim-server.

Encountered issues largely involve versioning and availability. For scim-server, the version listed on Maven central appears to be 2.3-SNAPSHOT which doesn't correspond to any valid tags in this GitHub repository.

Further, scim-spring-boot-starter doesn't seem to be present at all in the Maven central repository under Apache.

This mismatch between specifications and our implementation roadblocks is preventing us from leveraging the SCIMple project effectively. Any guidance or updates to address these issues would be greatly appreciated.

**Comment by bdemers** [comment]
Thanks for reaching out @heureuxchaquejour!

At the top of the tutorial there is this note:

> NOTE: Apache SCIMple is still in development, you must build Apache SCIMple from source.
> 
> git clone https://github.com/apache/directory-scimple.git
> cd directory-scimple
> ./mvnw install

That said, we are planning on doing an initial release in the immediate future, we would love your feedback!

**Comment by thanhvg** [comment]
Can you please provide an update on the initial release of `scimple`? It is so far the best java library for SCIM imo. However, the fact that it needs to be built from source is a concern to my team.

**Comment by bdemers** [comment]
I started cutting the release just before Christmas, but ran into a minor issue in the process with generating an aggregated javadoc-jar (i figured it out just before the break)

~~We'll try to get your changes in, and then cut a release directly after that!~~
(Sorry, I had you confused with @markusmueller, they had sent in a couple of fixes last week)

**Comment by recrsn** [comment]
@bdemers If you need help in specific testing or general ongoing library maintenance,I'll be happy to contribute.

My employer will also reimburse for my work since we are planning to use this in production in near future

**Comment by bdemers** [comment]
After the initial release, this should no longer be an issue.

@recrsn we would love any help! Testing, doc, fixes, blog posts, anything would be appreciated
