### ISSUE TITLE
sortOrder query parameter not handled and results in 404

### ISSUE THREAD

**Issue by BlueRui** [apache/directory-scimple#485]
The "sortOrder" parameter may not be handled properly. Having it in the query results in a 404 response.

I tried with the SpringBoot SCIM server example to learn about the library.
When only "sortBy" is used like "GET localhost:8080/v2/Users?sortBy=displayName", I can get a 200 OK response.
When "sortOrder" is added like "GET localhost:8080/v2/Users?sortBy=displayName&sortOrder=ascending". I get 404 Not Found.
![image](https://github.com/apache/directory-scimple/assets/23182566/e648993c-eb7f-4623-81e6-602af5d07348)

I tried setting supports sort to true in ServerConfiguration, but it made no difference. Did I miss anything?

**Comment by bdemers** [comment]
Thanks for opening this issue @BlueRui!
The values for the `sortOrder` are controlled by an enum, and it looks like the parsing is case sensitive, for example, `sortOrder=ASCENDING` seems to work.

Any chance you want to look into sending a pull request to fix the issue?
