### ISSUE TITLE
colon not accepted in file names on Windows

### ISSUE THREAD

**Issue by BlueRui** [apache/directory-scimple#491]
A few json resource files used for testing in "scim-spec\scim-spec-schema\src\test\resources\schemas\" have colons in their file names. Colons are not accepted in file names on Windows. This makes it impossible to checkout the project on a Windows system.

Changing colons to underscores in file names and corresponding tests would solve the problem.

**Comment by bdemers** [comment]
Thanks for reporting the issue!

Any chance you want send a PR?

**Comment by BlueRui** [comment]
Sure. Will send a PR after work.

**Comment by mattiahj** [comment]
I can confirm this is an issue.
