### ISSUE TITLE
Swagger doc

### ISSUE THREAD

**Issue by torbaAnton** [apache/directory-scimple#506]
Hi guys, this is more like a question, how do you generate swagger documentation?
I see endpoints are covered by swagger, but whenever I try to request any known swagger API I get:

```json
{
    "detail": "HTTP 404 Not Found",
    "status": "404",
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ]
} 
```

Is there any URL that I can call by default to get swagger documentation?

**Comment by bdemers** [comment]
The SCIM endpoints are annotated, but you would need to configure your endpoint to serve the Swagger/OpenAPI metadata.

Honestly, I'm not sure there is a lot of value in SCIMple providing this functionality at all (e.g. the annotations) the Swagger/OpenAPI response for the server are essentially fixed, all of the annotations could be replaced with a static OpenAPI file based on the SCIM rfcs.

I'd love feedback on this topic (it's not something I'd want to just remove if folks find it useful)
If it is useful, it may be possible to improve the support (possibly generate the spec from the SCIM metadata and remove the need for the Swagger annotations)

Another reason for NOT supporting the Swagger endpoint out of the box, is that it would require a dependency on the Servlet Runtime (currently only Jakarta EE Core is required).

All that said, adding the swagger endpoint to your SCIMple application should only require a couple extra steps:
https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5
