### ISSUE TITLE
[scim-server] Usage in SpringBoot breaks standard @RestController and SecurityFilters

### ISSUE THREAD

**Issue by 39otrebla** [apache/directory-scimple#575]
I've successfully integrated this library in Spring Boot 3.2.4, and it works like a charm (so thank you).

However, our SpringBoot application has to serve other HTTP endpoints besides SCIM ones, and we are having mainly two issues:

1. we implemented a test `@RestController` with a simple `@GetMapping("/test-endpoint")`, but calling this endpoint ends up invoking the SCIM server (which in turn does not find this path mapping and returns `404`).

2. it seems there's no way to configure a prefix for all SCIM endpoints (e.g. `/SCIM/**`. This makes it impossible to configure multiple `SecurityFilter(s)` based on the path prefix, which is required if the same SpringBoot application serves other resources

**Comment by 39otrebla** [comment]
Apologies, I found out just now that Jakarta Application was registered as `CondtionalOnMissingBean`.

For anyone having the same question, it is as simple as overriding the default `@Bean` for the Jakarta Application, using `@ApplicationPath("/prefix")`:

```java
// ScimServerApplication.java

@ApplicationPath("/scim")
public class ScimServerApplication extends Application {
    @Override
    public Set<Class<?>> getClasses() {
        return ScimResourceHelper.scimpleFeatureAndResourceClasses();
    }
}
```

And then:
```java
// MyApplication.java

@Bean
ServerConfiguration serverConfiguration() {
    return new ServerConfiguration()
            .setId("contoso.com")
            // all other configs
            .setBulkMaxOperations(50);
}

@Bean
Application scimApplication() {
    return new ScimServerApplication();
}
```

I confirm that both issues in the OP are solved. It may be worth mentioning in the doc.

**Comment by kkucybala** [comment]
These simple additions indeed fixed the problem for my project too, would be worthwhile adding it to the docs because anyone trying to integrate this library in any non-trivial service will have the same problem

**Comment by bdemers** [comment]
Great points!  
Does anyone want to take a quick pass at updating the README?
