### ISSUE TITLE
Question: Is there bidirectional sync support in Apache SCIMple?

### ISSUE THREAD

**Issue by harpreet86** [apache/directory-scimple#691]
If I have to sync data from service provider back to Identity provider, is that support provided by Apache SCIMple?

**Comment by bdemers** [comment]
Apache SCIMple provides a framework to create a SCIM server (receive data from an IdP) and a basic SCIM client (push data to an IdP).
Using the client, you would be able to push data back to your IdP.

If you don't think this question is answered please let me know and I'll re-open it!

**Comment by harpreet86** [comment]
Can you please share some examples for usage of SCIM Client.
