### ISSUE TITLE
Question: SCIM user and role mapping

### ISSUE THREAD

**Issue by harpreet86** [apache/directory-scimple#692]
I do not find any community to ask SCIM related doubts so raising this as a question here where I seek suggestion from you guys related to my query published https://stackoverflow.com/questions/79250220/scim-user-and-role-mapping 

> I have an application where the users are created in SCIM supported Identity Provider which I need to sync in my application(service provider here). This is achievable via SCIM.
> 
> Now, there are roles those are created in my application dynamically and I have to assign role(s) to the users in my application synced via SCIM.
> 
> I need suggestions here how should I decide which role(s) to assign to which user when user is synced via SCIM.
> 
> Also, as the roles are dynamically created in my application how should I flow this information back to Identity provider so that correct decision can be made which role to assign to which user while creating user in Identity provider.
> 
> Please share your opinions.

**Comment by bdemers** [comment]
Similar to the SO post, this is a bit off topic for us.  That said, if you are trying to use SCIMple as a SCIM implementation, and are looking for more general advice let us know!

NOTE: it's hard to answer your question without a lot more detail on your specific environment. Your best bet might be to contact your identity provider (or it's mailing lists) and look for suggestions there.
